name: rabies
channels:
  - simpleitk
  - defaults
  - conda-forge
dependencies:
  - blas=2.11=openblas
  - keepalive=0.5=py_1
  - libblas=3.8.0=11_openblas
  - libcblas=3.8.0=11_openblas
  - liblapack=3.8.0=11_openblas
  - liblapacke=3.8.0=11_openblas
  - multiprocess=0.70.8=py36h516909a_1
  - nibabel=2.3.1=pyh24bf2e0_0
  - nilearn=0.4.2=pyh24bf2e0_0
  - nipype=1.1.4=py36_0
  - pathos=0.2.4=py_0
  - pox=0.2.6=py_0
  - ppft=1.6.6.1=py36_0
  - prov=1.5.0=py36_0
  - pydicom=1.3.0=py_0
  - rdflib=4.2.2=py36_1000
  - sparqlwrapper=1.8.2=py36_1000
  - xvfbwrapper=0.2.9=py36_1000
  - _libgcc_mutex=0.1=main
  - apipkg=1.5=py36_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.1.0=py36_1
  - ca-certificates=2019.5.15=1
  - cairo=1.14.12=h8948797_3
  - certifi=2019.6.16=py36_1
  - click=7.0=py36_0
  - cloudpickle=1.2.2=py_0
  - cycler=0.10.0=py36_0
  - cython=0.29.13=py36he6710b0_0
  - cytoolz=0.10.0=py36h7b6447c_0
  - dask-core=2.3.0=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py36_1
  - dill=0.3.0=py36_0
  - execnet=1.6.1=py_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - funcsigs=1.0.2=py36_0
  - future=0.17.1=py36_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py36h7918eee_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.4=hb1b8bf9_0
  - html5lib=1.0.1=py_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.5.0=py36_0
  - importlib_metadata=0.19=py36_0
  - isodate=0.6.0=py_1
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py36he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopenblas=0.3.6=h5a2b251_1
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - lxml=4.4.1=py36hefd8a0e_0
  - matplotlib=3.1.1=py36h5429711_0
  - mock=3.0.5=py36_0
  - more-itertools=7.2.0=py36_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.3=py_0
  - numpy=1.16.2=py36h99e49ec_0
  - numpy-base=1.16.2=py36h2f8d375_0
  - olefile=0.46=py36_0
  - openssl=1.1.1d=h7b6447c_1
  - packaging=19.1=py36_0
  - pandas=0.25.1=py36he6710b0_0
  - pango=1.42.4=h049681c_0
  - pcre=8.43=he6710b0_0
  - pillow=6.1.0=py36h34e0f95_0
  - pip=19.2.2=py36_0
  - pixman=0.38.0=h7b6447c_0
  - pluggy=0.12.0=py_0
  - psutil=5.6.3=py36h7b6447c_0
  - py=1.8.0=py36_0
  - pydotplus=2.0.2=py36_1
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pytest=5.0.1=py36_0
  - pytest-forked=1.0.2=py36_0
  - pytest-xdist=1.28.0=py_0
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - python-graphviz=0.10.1=py_0
  - pytz=2019.2=py_0
  - pywavelets=1.0.3=py36hdd07704_1
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-image=0.15.0=py36he6710b0_0
  - scikit-learn=0.20.0=py36h22eb022_1
  - scipy=1.3.1=py36he2b7bc3_0
  - setuptools=41.0.1=py36_0
  - simplejson=3.16.0=py36h14c3975_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h7b6447c_0
  - tqdm=4.32.1=py_0
  - traits=5.1.1=py36h7b6447c_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - zipp=0.5.2=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - simpleitk=1.2.2=py36hf484d3e_0
  - pip:
    - bids-validator==1.2.4
    - dask==2.3.0
    - docopt==0.6.2
    - num2words==0.5.10
    - patsy==0.5.1
    - pybids==0.9.4
    - sqlalchemy==1.3.10

