blank_issues_enabled: false
contact_links:
  - name: Troubleshooting Guide
    url: https://github.com/CoBrALab/RABIES/blob/master/docs/troubleshooting.md
    about: Check our troubleshooting guide for common issues and solutions
